name: Build 

on:
  push:
    branches: [ "main" ]

jobs:
  Build-run:
    name: build and run the js test project
    runs-on: windows-latest
    
    steps:
    - run: npm install node
      name: Install node.js
    - run: node -v
      name: Check node Installation

    - name: Checkout the code from Github repo 
      uses: actions/checkout@v3
    - run:  node index.html
      name: run JS project using Node.js
      
